const CharCounterApp = {
  data() {
    const RUS_LTR = 2
    const LAT_LTR = 2
    const RUS_SYM = 2
    const LAT_SYM = 1
    const make_symbol = (count, pattern, view) => { return [char, {count: count, pattern: pattern, view: (view ? view : pattern)}] }
    const rl = new Map([
      make_symbol(5, 'а'),
      make_symbol(3, 'б'),
      make_symbol(3, 'в'),
      make_symbol(3, 'г'),
      make_symbol(3, 'д'),
      make_symbol(3, 'е'),
      make_symbol(2, 'ё'),
      make_symbol(2, 'э'),
      make_symbol(2, 'ж'),
      make_symbol(2, 'з'),
      make_symbol(5, 'и'),
      make_symbol(1, 'й'),
      make_symbol(3, 'к'),
      make_symbol(3, 'л'),
      make_symbol(3, 'м'),
      make_symbol(5, 'н'),
      make_symbol(5, 'о'),
      make_symbol(2, 'п'),
      make_symbol(3, 'р'),
      make_symbol(4, 'с'),
      make_symbol(4, 'т'),
      make_symbol(3, 'у'),
      make_symbol(2, 'ф'),
      make_symbol(3, 'х'),
      make_symbol(3, 'ц'),
      make_symbol(3, 'ч'),
      make_symbol(2, 'ь'),
      make_symbol(1, 'ъ'),
      make_symbol(2, 'ы'),
      make_symbol(2, 'ю'),
      make_symbol(4, 'я'),
      make_symbol(2, 'ш'),
      make_symbol(2, 'щ'),
    ])
    const ru = new Map([
      make_symbol(4, 'А'),
      make_symbol(1, 'Б'),
      make_symbol(3, 'В'),
      make_symbol(2, 'Г'),
      make_symbol(2, 'Д'),
      make_symbol(2, 'Е'),
      make_symbol(1, 'Ё'),
      make_symbol(1, 'Э'),
      make_symbol(2, 'Ж'),
      make_symbol(2, 'З'),
      make_symbol(2, 'И'),
      make_symbol(1, 'Й'),
      make_symbol(2, 'К'),
      make_symbol(2, 'Л'),
      make_symbol(2, 'М'),
      make_symbol(3, 'Н'),
      make_symbol(3, 'О'),
      make_symbol(2, 'П'),
      make_symbol(2, 'Р'),
      make_symbol(3, 'С'),
      make_symbol(3, 'Т'),
      make_symbol(3, 'У'),
      make_symbol(2, 'Ф'),
      make_symbol(1, 'Х'),
      make_symbol(1, 'Ц'),
      make_symbol(1, 'Ч'),
      make_symbol(1, 'Ь'),
      make_symbol(1, 'Ъ'),
      make_symbol(1, 'Ы'),
      make_symbol(2, 'Ю'),
      make_symbol(2, 'Я'),
      make_symbol(1, 'Ш'),
      make_symbol(1, 'Щ'),
    ])
    const rs = new Map([
      make_symbol(5, '0'),
      make_symbol(3, '1'),
      make_symbol(3, '2'),
      make_symbol(3, '3'),
      make_symbol(3, '4'),
      make_symbol(3, '5'),
      make_symbol(3, '6'),
      make_symbol(3, '7'),
      make_symbol(3, '8'),
      make_symbol(3, '9'),
      make_symbol(4, 'I'),
      make_symbol(2, 'V'),
      make_symbol(1, 'X'),
      make_symbol(1, 'L'),
      make_symbol(4, '.'),
      make_symbol(3, ','),
      make_symbol(3, '/'),
      make_symbol(1, '!'),
      make_symbol(3, '−'),
      make_symbol(1, '&'),
      make_symbol(1, '“|«', '“'),
      make_symbol(1, 'ˮ|»', 'ˮ'),
      make_symbol(1, '˶'),
      make_symbol(1, '…|...', '…'),
      make_symbol(1, ';'),
      make_symbol(1, ':'),
      make_symbol(1, '\''),
      make_symbol(1, '?'),
    ])
    const ll = new Map([
      make_symbol(6, 'a'),
      make_symbol(2, 'b'),
      make_symbol(2, 'с'),
      make_symbol(2, 'd'),
      make_symbol(5, 'e'),
      make_symbol(2, 'f'),
      make_symbol(2, 'g'),
      make_symbol(3, 'h'),
      make_symbol(5, 'i'),
      make_symbol(1, 'j'),
      make_symbol(2, 'k'),
      make_symbol(5, 'l'),
      make_symbol(2, 'm'),
      make_symbol(7, 'n'),
      make_symbol(5, 'o'),
      make_symbol(2, 'p'),
      make_symbol(1, 'r'),
      make_symbol(5, 'q'),
      make_symbol(3, 's'),
      make_symbol(5, 't'),
      make_symbol(2, 'u'),
      make_symbol(1, 'v'),
      make_symbol(1, 'w'),
      make_symbol(1, 'x'),
      make_symbol(2, 'y'),
      make_symbol(2, 'z'),
    ])
    const lu = new Map([
      make_symbol(2, 'A'),
      make_symbol(1, 'B'),
      make_symbol(2, 'С'),
      make_symbol(1, 'D'),
      make_symbol(2, 'E'),
      make_symbol(1, 'F'),
      make_symbol(2, 'G'),
      make_symbol(1, 'H'),
      make_symbol(1, 'I'),
      make_symbol(2, 'J'),
      make_symbol(1, 'K'),
      make_symbol(1, 'L'),
      make_symbol(1, 'M'),
      make_symbol(1, 'N'),
      make_symbol(1, 'O'),
      make_symbol(1, 'P'),
      make_symbol(2, 'R'),
      make_symbol(1, 'Q'),
      make_symbol(2, 'S'),
      make_symbol(2, 'T'),
      make_symbol(1, 'U'),
      make_symbol(1, 'V'),
      make_symbol(1, 'W'),
      make_symbol(1, 'X'),
      make_symbol(2, 'Y'),
      make_symbol(1, 'Z'),
    ])
    const ls = new Map([
      make_symbol(6, '0'),
      make_symbol(3, '1'),
      make_symbol(4, '2'),
      make_symbol(4, '3'),
      make_symbol(3, '4'),
      make_symbol(3, '5'),
      make_symbol(3, '6'),
      make_symbol(3, '7'),
      make_symbol(3, '8'),
      make_symbol(3, '9'),
      make_symbol(1, 'www'),
      make_symbol(1, 'ʼ'),
      make_symbol(4, '.'),
      make_symbol(3, ','),
      make_symbol(4, '/'),
      make_symbol(1, '!'),
      make_symbol(4, '−'),
      make_symbol(1, '&'),
      make_symbol(1, '„'),
      make_symbol(1, '“'),
      make_symbol(1, '”'),
      make_symbol(1, '…|...', '…'),
      make_symbol(1, ':'),
      make_symbol(1, ';'),
      make_symbol(1, '@'),
      make_symbol(1, '?'),
    ])
    const space = make_symbol(8, ' ')
    const alphabet_max = new Map([...rs, ...rb, ...ls, ...lb, ...s])
    var alphabet = new Map()
    alphabet_max.forEach( (value, char) => { alphabet.set(char, 0) } )
    return {
      text: '',
      RUS_LTR: 2,
      LAT_LTR: 2,
      RUS_SYM: 2,
      LAT_SYM: 1,
      alphabet: alphabet,
      alphabet_max: alphabet_max,
      rs: [...rs.keys()],
      rb: [...rb.keys()],
      ls: [...ls.keys()],
      lb: [...lb.keys()],
      s: [...s.keys()],
    }
  },
  watch: {
    text: function (newText, oldText) {
      this.alphabet.forEach( (value, char) => { this.alphabet.set(char, 0) }, this )
      newText.split('').forEach(char => { this.alphabet.set(char, this.alphabet.get(char)+1) }, this);
    }
  },
  created: function () {
    this.text = "Небольшой пример текста, в котором есть избыточное использование символов"
  }
}

Vue.createApp(CharCounterApp).mount('#char-counter')
